server:
 port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:testdb2
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true